import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app",
};
export default function Blog() {
  return (
    <div>
      <h1>Blog Pages</h1>
    </div>
  );
}
